extension["tom扩"]={
	intro:"",
	author:"诸神无限",
	netdisk:"",
	forum:"",
	version:"1.0",
	files:["info.json","README.md","gaoJieQiShi.jpg","shengTangMuShi.jpg","huangMoNvWu.jpg","longQiShi.jpg","daiXingZhe.jpg","shouRenJun.jpg","shouLingLieShou.jpg","yingLiuWuShi.jpg","LICENSE","daiXingZhe.jpg","eMoWenZhang.jpg","fangYuZhuangTai.jpg","gaoJieQiShi.jpg","gongJiZhuangTai.jpg","huangMoNvWu.jpg","info.json","jianHuang.jpg","LICENSE","liuLiNvWu.jpg","longJianShi.jpg","longQiShi.jpg","longShuShi.jpg","lvXingShangRen.jpg","README.md","shaXueZhiShi.jpg","shengTangMuShi.jpg","shiKongShaLou.jpg","shouLingLieShou.jpg","shouRenJun.jpg","shuangMianNvLang.jpg","tianShiWenZhang.jpg","yeQiShi.jpg","yingLiuWuShi.jpg"],
	size:"11.9MB"
};